### ISSUE TITLE
New task

### ISSUE THREAD

**Issue by mitchell-liatrio** [liatrio-enterprise/codeql-examples#34]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```

**Comment by mitchell-liatrio** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```
